update cb_courses set course_thumbnail = 'corejava.png' where course_name = 'Core Java Basics'; 
update cb_courses set course_thumbnail = 'corejavaadv.png' where course_name = 'Core Java Advanced';
update cb_courses set course_thumbnail = 'logicalcoding.png' where course_name = 'Logical coding';
update cb_courses set course_thumbnail = 'ds.png' where course_name = 'Data Structures';
update cb_courses set course_thumbnail = 'algo.png' where course_name = 'Algorithms';
update cb_courses set course_thumbnail = 'mysql.jpg' where course_name = 'SQL';
update cb_courses set course_thumbnail = 'jdbc.jpg' where course_name = 'JDBC';
update cb_courses set course_thumbnail = 'servlets.jpg' where course_name = 'Servlets';
update cb_courses set course_thumbnail = 'jsp.jpg' where course_name = 'JSP';
update cb_courses set course_thumbnail = 'hibernate.jpg' where course_name = 'Hibernate';
update cb_courses set course_thumbnail = 'spring.png' where course_name = 'Spring';
update cb_courses set course_thumbnail = 'springboot.png' where course_name = 'Spring Boot';
update cb_courses set course_thumbnail = 'springmcr.png' where course_name = 'Spring Microservice';
update cb_courses set course_thumbnail = 'javascript.jpg' where course_name = 'JavaScript';
update cb_courses set course_thumbnail = 'angular.jpg' where course_name = 'Angular';
update cb_courses set course_thumbnail = 'webservice.png' where course_name = 'Webservices';
update cb_courses set course_thumbnail = 'projdev.png' where course_name = 'Project Development';